### ISSUE TITLE
Install and run instructions 

### ISSUE THREAD

**Issue by pseudozach** [fiatjaf/bridgeaddr#2]
Setup instructions are great but I know nothing about how to run these go files. Can you please add install instructions and which port this thing will run on my machine?

**Comment by fiatjaf** [comment]
You don't have to run it, that's the idea. Just point the DNS records to my instance.

---

But if you really want to run it I can tell you here:

Install Go from here: https://golang.org/dl/, run `make`, then run the binary: `./bridgeaddr`. Required environment variables are here: https://github.com/fiatjaf/bridgeaddr/blob/9d75b0bbf7018b49c1478e9b1ea3c93a9f8c8437/main.go#L19-L20

Then you need to setup your reverse proxy server (e.g. Nginx, Caddy) to accept calls from any domain and proxy them to your `bridgeaddr`.

In my global `Caddyfile` I have this rule at the end that also issues TLS certs for everyone automatically:

```
:443 {
    reverse_proxy localhost:12345

    tls fiatjaf@gmail.com {
      on_demand
    }
}
```

**Comment by pseudozach** [comment]
Ah ok thank you! I had misread and misunderstood the whole thing. That's indeed easier.
What if I don't want to add a cname for the whole domain just a subdomain pay.pseudozach.com, the instructions are the same right?

**Comment by fiatjaf** [comment]
Yes, but that's bad experience for your payers, although hard to work around.
The solutions I have for that are:
1. Use the subdomain, but use your own reverse proxy at pseudozach.com to forward `/.well-known/lnurlp` to pay.pseudozach.com
2. Move your website to `www.pseudozach.com` like in the old days, and use the bridgeaddr `_redirect`  directive to redirect people visiting your root domain to the www domain
3. Do nothing, since we're just playing here
4. Use a Satdress instance of your own domain, like bitmia.com or payaddress.co

**Comment by pseudozach** [comment]
wow it works! I didn't change anything just setup for same lnbits instructions but host = pay.pseudozach.com 

What did you mean bad experience for payers? you mean harder to type?I don't actually expect anyone to even type pseudozach without copy/paste so it's ok :)

**Comment by pseudozach** [comment]
thanks!
